Homework 2
================
Jyoti Kumar

``` r
library(tidyverse)
```

    ## ── Attaching packages ──────────────────────────────────────────────────────────────────────── tidyverse 1.3.0 ──

    ## ✓ ggplot2 3.3.2     ✓ purrr   0.3.4
    ## ✓ tibble  3.0.3     ✓ dplyr   1.0.2
    ## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
    ## ✓ readr   1.3.1     ✓ forcats 0.5.0

    ## ── Conflicts ─────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(readxl)
```

## Problem 1

``` r
trashwheel_df = 
  read_xlsx(
  "./Data Problem1/Trash-Wheel-Collection-Totals-7-2020-1.xlsx",
  sheet = "Mr. Trash Wheel", 
  range = cell_cols("A:N")) %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>%
  mutate(
  sports_balls = round(sports_balls),
  sports_balls = as.integer(sports_balls)
  )
```

``` r
precip_2018 =
  read_excel(
    "./Data Problem1/Trash-Wheel-Collection-Totals-7-2020-1.xlsx",
    sheet = "2018 Precipitation",
    skip = 1
  ) %>% 
  janitor::clean_names() %>% 
  drop_na(month) %>% 
  mutate(year = 2018) %>% 
  relocate(year)
```

``` r
precip_2017 =
  read_excel(
    "./Data Problem1/Trash-Wheel-Collection-Totals-7-2020-1.xlsx",
    sheet = "2017 Precipitation",
    skip = 1
  ) %>% 
  janitor::clean_names() %>% 
  drop_na(month) %>% 
  mutate(year = 2017) %>% 
  relocate(year)
```

``` r
precip_df =
  bind_rows(precip_2017, precip_2018) %>% 
  mutate(month = month.name[month])
```

The dataset contains information from the Mr. Trashwheel trash collector
in Baltimore, Maryland. The data reflects the year, month, tashcollected
and also tells us about some specific kinds of trash collected by the
collector. The total number of rows in the dataset is 416 rows.
Additional sheets in the dataframe include the monthly precipitation
from 2014- 2019. The precipitation dataset we created contains 24 rows
and contains information about the total monthly precipitation in the
years 2017 and 2018. The total precipitation in 2018 was 70.33 in.

## Problem 2

``` r
transit_df =
  read_csv(
    "./Data Problem2/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  janitor::clean_names() %>% 
select(line, station_name, station_latitude, station_longitude, route1:route11, entry, vending, entrance_type, ada) %>% 
mutate(entry = recode(entry, "YES" = "TRUE", "NO" = "FALSE"), entry = as.logical(entry))
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_double(),
    ##   Route9 = col_double(),
    ##   Route10 = col_double(),
    ##   Route11 = col_double(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

``` r
skimr::skim(transit_df)
```

|                                                  |             |
| :----------------------------------------------- | :---------- |
| Name                                             | transit\_df |
| Number of rows                                   | 1868        |
| Number of columns                                | 19          |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |             |
| Column type frequency:                           |             |
| character                                        | 11          |
| logical                                          | 2           |
| numeric                                          | 6           |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |             |
| Group variables                                  | None        |

Data summary

**Variable type: character**

| skim\_variable | n\_missing | complete\_rate | min | max | empty | n\_unique | whitespace |
| :------------- | ---------: | -------------: | --: | --: | ----: | --------: | ---------: |
| line           |          0 |           1.00 |   5 |  17 |     0 |        36 |          0 |
| station\_name  |          0 |           1.00 |   4 |  39 |     0 |       356 |          0 |
| route1         |          0 |           1.00 |   1 |   2 |     0 |        24 |          0 |
| route2         |        848 |           0.55 |   1 |   2 |     0 |        20 |          0 |
| route3         |       1374 |           0.26 |   1 |   2 |     0 |        18 |          0 |
| route4         |       1547 |           0.17 |   1 |   1 |     0 |        13 |          0 |
| route5         |       1630 |           0.13 |   1 |   1 |     0 |        12 |          0 |
| route6         |       1741 |           0.07 |   1 |   1 |     0 |         7 |          0 |
| route7         |       1788 |           0.04 |   1 |   2 |     0 |         7 |          0 |
| vending        |          0 |           1.00 |   2 |   3 |     0 |         2 |          0 |
| entrance\_type |          0 |           1.00 |   4 |   9 |     0 |         7 |          0 |

**Variable type: logical**

| skim\_variable | n\_missing | complete\_rate | mean | count               |
| :------------- | ---------: | -------------: | ---: | :------------------ |
| entry          |          0 |              1 | 0.94 | TRU: 1753, FAL: 115 |
| ada            |          0 |              1 | 0.25 | FAL: 1400, TRU: 468 |

**Variable type: numeric**

| skim\_variable     | n\_missing | complete\_rate |    mean |   sd |      p0 |     p25 |     p50 |     p75 |    p100 | hist  |
| :----------------- | ---------: | -------------: | ------: | ---: | ------: | ------: | ------: | ------: | ------: | :---- |
| station\_latitude  |          0 |           1.00 |   40.73 | 0.07 |   40.58 |   40.69 |   40.73 |   40.77 |   40.90 | ▂▅▇▃▂ |
| station\_longitude |          0 |           1.00 | \-73.94 | 0.06 | \-74.03 | \-73.99 | \-73.96 | \-73.91 | \-73.76 | ▇▆▃▂▁ |
| route8             |       1820 |           0.03 |    2.98 | 1.94 |    1.00 |    1.00 |    4.00 |    5.00 |    5.00 | ▇▁▁▂▇ |
| route9             |       1840 |           0.01 |    2.54 | 1.17 |    2.00 |    2.00 |    2.00 |    2.00 |    5.00 | ▇▁▁▁▂ |
| route10            |       1845 |           0.01 |    3.00 | 0.00 |    3.00 |    3.00 |    3.00 |    3.00 |    3.00 | ▁▁▇▁▁ |
| route11            |       1845 |           0.01 |    7.00 | 0.00 |    7.00 |    7.00 |    7.00 |    7.00 |    7.00 | ▁▁▇▁▁ |

``` r
names(transit_df)
```

    ##  [1] "line"              "station_name"      "station_latitude" 
    ##  [4] "station_longitude" "route1"            "route2"           
    ##  [7] "route3"            "route4"            "route5"           
    ## [10] "route6"            "route7"            "route8"           
    ## [13] "route9"            "route10"           "route11"          
    ## [16] "entry"             "vending"           "entrance_type"    
    ## [19] "ada"

The dataset in Problem 2 is about the NYC transit data. It talks about
the entry and exit points of each station in the city, their latitudes
and longitudes and the routes that run at each station. There are a
total of 19 Variables in the dataset. The Variables in the dataset are:
line, station\_name, route1, route2, vending, entrance\_type etc. my
data cleaning steps include: line, station\_name, station\_latitude,
station\_longitude, route1, route2, route3, route4, route5, route6,
route7, route8, route9, route10, route11, entry, vending,
entrance\_type, ada . The dimensions of my dataset are: 1868 \* 19 .
According to me, I belive that the data is tidy.

``` r
distinct(transit_df, station_name)
```

    ## # A tibble: 356 x 1
    ##    station_name            
    ##    <chr>                   
    ##  1 25th St                 
    ##  2 36th St                 
    ##  3 45th St                 
    ##  4 53rd St                 
    ##  5 59th St                 
    ##  6 77th St                 
    ##  7 86th St                 
    ##  8 95th St                 
    ##  9 9th St                  
    ## 10 Atlantic Av-Barclays Ctr
    ## # … with 346 more rows

``` r
filter(transit_df, !(ada == FALSE))
```

    ## # A tibble: 468 x 19
    ##    line  station_name station_latitude station_longitu… route1 route2 route3
    ##    <chr> <chr>                   <dbl>            <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Av… Atlantic Av…             40.7            -74.0 B      Q      D     
    ##  2 4 Av… DeKalb Av                40.7            -74.0 B      Q      R     
    ##  3 4 Av… DeKalb Av                40.7            -74.0 B      Q      R     
    ##  4 4 Av… DeKalb Av                40.7            -74.0 B      Q      R     
    ##  5 4 Av… DeKalb Av                40.7            -74.0 B      Q      R     
    ##  6 4 Av… DeKalb Av                40.7            -74.0 B      Q      R     
    ##  7 4 Av… DeKalb Av                40.7            -74.0 B      Q      R     
    ##  8 4 Av… Pacific St               40.7            -74.0 B      Q      D     
    ##  9 4 Av… Pacific St               40.7            -74.0 B      Q      D     
    ## 10 42nd… Grand Centr…             40.8            -74.0 GS     4      5     
    ## # … with 458 more rows, and 12 more variables: route4 <chr>, route5 <chr>,
    ## #   route6 <chr>, route7 <chr>, route8 <dbl>, route9 <dbl>, route10 <dbl>,
    ## #   route11 <dbl>, entry <lgl>, vending <chr>, entrance_type <chr>, ada <lgl>

``` r
filter(transit_df, !(vending == "YES"))
```

    ## # A tibble: 183 x 19
    ##    line  station_name station_latitude station_longitu… route1 route2 route3
    ##    <chr> <chr>                   <dbl>            <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Av… 53rd St                  40.6            -74.0 R      <NA>   <NA>  
    ##  2 4 Av… 77th St                  40.6            -74.0 R      <NA>   <NA>  
    ##  3 4 Av… 9th St                   40.7            -74.0 F      G      R     
    ##  4 4 Av… Bay Ridge Av             40.6            -74.0 R      <NA>   <NA>  
    ##  5 42nd… Grand Centr…             40.8            -74.0 GS     4      5     
    ##  6 42nd… Grand Centr…             40.8            -74.0 GS     4      5     
    ##  7 6 Av… 7th Av                   40.7            -74.0 F      <NA>   <NA>  
    ##  8 6 Av… 7th Av                   40.7            -74.0 F      <NA>   <NA>  
    ##  9 6 Av… 7th Av                   40.7            -74.0 F      <NA>   <NA>  
    ## 10 6 Av… 7th Av                   40.7            -74.0 F      <NA>   <NA>  
    ## # … with 173 more rows, and 12 more variables: route4 <chr>, route5 <chr>,
    ## #   route6 <chr>, route7 <chr>, route8 <dbl>, route9 <dbl>, route10 <dbl>,
    ## #   route11 <dbl>, entry <lgl>, vending <chr>, entrance_type <chr>, ada <lgl>

The number of distinct stations include: 356. The number of ada
compliant stations is: 468. There are 183 stations that allow entry
without vending.
